

name: Deploy Astro to S3

on:
  push:
    branches: [ main ]   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      
      - name: Install dependencies
        run: npm ci

      
      - name: Build Astro project
        run: npm run build

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Sync dist/ to S3
        run: aws s3 sync ./dist s3://myportfoliofrontend --delete
